### ISSUE TITLE
Incorrect Code Example in Python Functions Lesson

### ISSUE THREAD

**Issue by angibor** [learn-co-curriculum/dsc-data-serialization-lab#14]
<**Description:**
I noticed an issue with the code example provided in the "Python Functions" lesson in the Intermediate Python module. The code example for defining a function with default arguments is incorrect and may confuse learners.

**Context:**
The problem occurs in the section titled "Default Arguments." The example code provided is as follows:

def greet(name, greeting="Hello", punctuation):
    return greeting + " " + name + punctuation

result = greet("Alice", "?")
print(result)
Issue:
The issue with this code example is that the parameter punctuation is defined after the parameter with the default value (greeting). In Python, when defining a function with default arguments, all parameters with default values must come after the parameters without default values. This code will raise a SyntaxError when executed.

**Impact:**
This issue can confuse learners who are trying to understand how to define functions with default arguments in Python. It may lead to incorrect code being written and frustration among learners who are not familiar with Python's function syntax.

**Suggested Solution:**
I suggest modifying the code example as follows:

def greet(name, greeting="Hello", punctuation="?"):
    return greeting + " " + name + punctuation

result = greet("Alice")
print(result)
This revised code properly places the parameter with the default value at the end, and it provides a default value for the punctuation parameter. This will ensure the code runs without errors and accurately demonstrates the concept to learners.

**Comment by KelvinBrannonJr** [comment]
I would like to help with this issue.

**Comment by angibor** [comment]
Hi Kelvin 
kindly proceed to assist

**Comment by jessepisel** [comment]
thanks for opening this issue @angibor :wave:. Can you please link to the repo that contains this issue?

**Comment by Cheffrey2000** [comment]
This issue does not pertain to this repository. I am closing this issue, but please feel free to open it in the relevant repository if it is still an issue.
