### ISSUE TITLE
The lab is not loading

### ISSUE THREAD

**Issue by james-kibunja** [learn-co-curriculum/dsc-data-serialization-lab#22]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [x] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
@james-kibunja May you please drop in the Canvas link? It will help us trouble shoot. Thanks.

**Comment by jessepisel** [comment]
@bpurdy-ds It should have come from [this course](https://moringa.instructure.com/courses/514) but I cannot find any Saturn Cloud links for this lab in the course. All I can find is the [cumulative lab](https://moringa.instructure.com/courses/514/assignments/35593?module_item_id=75218)

**Comment by bpurdy-ds** [comment]
So please reopen if Jesse's comment above did not answer your question.
